### ISSUE TITLE
Release 5.8-arduino9 fails with ESP8266 package

### ISSUE THREAD

**Issue by igrr** [arduino/ctags#9] opened 2016-03-09 11:18 UTC
We are using nightly Arduino builds in our CI build, and noticed that our builds started failing two days ago.
Reverting ctags to 5.8-arduino7 fixes the issue.

I'll check what's wrong later today and post more info, just wanted to give a notice to @cmaglie @facchinm. Please don't release Arduino 1.6.8 with this version of ctags :)

**Comment by facchinm** [comment] 2016-03-09 11:23
Can you give us more infos on the failing test? our test suite (ctags + builder) shows no regression at all...

**Comment by igrr** [comment] 2016-03-09 11:43
Some forward declarations are not generated in CaptivePortalAdvanced sample (within DNSServer library). I will upload ctags output shortly.

**Comment by igrr** [comment] 2016-03-09 12:12
Output of two ctags versions when building the following sketch:

``` c++
#include <memory>

void setup() {
  test();
}

void loop() {}

void test() {}
```

[arduino-ctags-5.8-arduino7.txt](https://github.com/arduino/ctags/files/165078/arduino-ctags-5.8-arduino7.txt)
[arduino-ctags-5.8-arduino9.txt](https://github.com/arduino/ctags/files/165077/arduino-ctags-5.8-arduino9.txt)

5.8-arduino9 version stops after `__move_if_noexcept_cond`, while an older version continues to generate output after that point.

arduino-builder command line was:
`
/Users/igrokhotkov/projects/esp8266/arduino.cc/master/build/macosx/work/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware "/Users/igrokhotkov/projects/esp8266/arduino.cc/master/build/macosx/work/Arduino.app/Contents/Java/hardware" -hardware "/Users/igrokhotkov/Library/Arduino15/packages" -tools "/Users/igrokhotkov/projects/esp8266/arduino.cc/master/build/macosx/work/Arduino.app/Contents/Java/tools-builder" -tools "/Users/igrokhotkov/projects/esp8266/arduino.cc/master/build/macosx/work/Arduino.app/Contents/Java/hardware/tools/avr" -tools "/Users/igrokhotkov/Library/Arduino15/packages" -built-in-libraries "/Users/igrokhotkov/projects/esp8266/arduino.cc/master/build/macosx/work/Arduino.app/Contents/Java/libraries" -libraries "/Users/igrokhotkov/Documents/Arduino/libraries" -fqbn=esp8266:esp8266:generic:UploadTool=esptool,CpuFrequency=80,FlashFreq=40,FlashMode=dio,UploadSpeed=115200,FlashSize=512K64,ResetMethod=ck,Debug=Disabled,DebugLevel=None____ -ide-version=10607 -build-path "/var/folders/15/ybtbgzpj7636vv4wp92l2c700000gn/T/build948012c8c0a43aeaf43878b544675a06.tmp" -warnings=more -prefs=build.warn_data_percentage=75 -verbose "/var/folders/15/ybtbgzpj7636vv4wp92l2c700000gn/T/arduino_948012c8c0a43aeaf43878b544675a06/sketch_mar09a.ino"
`

**Comment by facchinm** [comment] 2016-03-09 14:55
Ok, bug spotted, the function "crashing" ctags was

```
    noexcept(__and_<is_nothrow_move_constructible<_Tp>,
             is_nothrow_move_assignable<_Tp>>::value)
```

because the `>>` rune was interpreted as a shift.
Reverting to the original behaviour fixes the issue (5dbd712 )

**Comment by facchinm** [comment] 2016-03-10 08:29
Closing as fixed by 5dbd712 (hopefully :smile: )

**Closed as completed by facchinm** 2016-03-10 08:29 UTC

**Comment by igrr** [comment] 2016-03-10 08:50
I can verify it works now, thanks :+1:

Would you consider adding the following sketch to arduino-builder test suite? (a-la "sketch_with_c++11_headers_included")

``` c++
#include <memory>
#include <functional>
void setup() {
  test();
}
void loop() {}
void test() {}
```

Since you already use SAM core in the test suite, you can compile it for Arduino Due. This gives the same result as for the ESP8266, before the fix.

**Comment by facchinm** [comment] 2016-03-10 08:57
sure, we'll be adding the test later today ;)
Thanks for the heads-up!
